# Generated by Django 5.2.6 on 2025-10-05 14:15

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cartype_drivetype_feature_safetyfeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits and may start with +.', regex='^\\+?\\d+$')]),
        ),
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='make',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name'),
        ),
    ]
