# Generated by Django 5.2.6 on 2025-10-05 14:17

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_inquiry_phone_alter_make_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelname',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='modelname',
            constraint=models.UniqueConstraint(models.F('make'), django.db.models.functions.text.Lower('name'), name='uniq_make_lower_name'),
        ),
    ]
