# Generated by Django 5.2.6 on 2025-10-05 14:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_modelname_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='safetyfeature',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='cartype',
            name='type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='condition',
            name='type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='drivetype',
            name='type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='safetyfeature',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='type',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='cartype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('type'), name='unique_car_lower_type'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_color_lower_name'),
        ),
        migrations.AddConstraint(
            model_name='condition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('type'), name='unique_condition_lower_type'),
        ),
        migrations.AddConstraint(
            model_name='drivetype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('type'), name='unique_drive_lower_type'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_feature_lower_name'),
        ),
        migrations.AddConstraint(
            model_name='fueltype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('type'), name='unique_fuel_lower_type'),
        ),
        migrations.AddConstraint(
            model_name='safetyfeature',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_safety_feature_lower_name'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_status_lower_name'),
        ),
        migrations.AddConstraint(
            model_name='transmission',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('type'), name='unique_transmission_lower_type'),
        ),
    ]
