# Generated by Django 5.2.6 on 2025-10-18 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_inquirycomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquirycomments',
            name='listing',
        ),
        migrations.AddField(
            model_name='inquirycomments',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry', to='api.inquiry'),
        ),
    ]
